- name: copy join command to worker nodes
  copy:
    src: /tmp/kubernetes_join_command
    dest: /tmp/kubernetes_join_command
    mode: 0777

- name: join worker nodes with controller
  command: sh /tmp/kubernetes_join_command
  register: joined_or_not
  ignore_errors: true

- name: output node join status
  debug:
    msg: "{{ joined_or_not.stdout }}"
