- name: add ssh key for ansible user
  tags: always
  authorized_key:
    user: ansible
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINbglM+Y94uo8jWayNpL28Yj0heHf9acymPq+8ySqkd2 ansible"

- name: install containerd
  tags: containerd
  apt:
    name:
      - containerd
    state: latest

- name: create containerd directory
  tags: containderd
  file:
    path: /etc/containerd
    state: directory
    owner: root
    group: root
    mode: 0755

- name: copy containerd config.toml
  tags: containerd
  copy:
    src: containerd_config
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: 0644

- name: enable containerd service, and enable persistently
  tags: containerd
  service:
    name: containerd
    enabled: yes

- name: restart containerd
  tags: containerd
  service:
    name: containerd
    state: restarted

- name: make swap inactive
  command: swapoff -a

- name: remove swap entry from /etc/fstab.
  lineinfile:
    path: /etc/fstab
    regexp: swap
    state: absent
  register: swap_disabled

- name: change sysctl config to allow IP forwarding
  lineinfile:
    path: /etc/sysctl.conf
    regexp: '^#net.ipv4.ip_forward' # ^ means beginning of line
    line: net.ipv4.ip_forward=1
  register: ip_forwarding # var to denote change. Can be called anything

- name: apply new sysctl settings
  command: sudo sysctl --system

- name: create k8s.conf module
  tags: k8s
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: 'br_netfilter'
    owner: root
    group: root
    mode: 0644

- name: import the k8s repo apt key
  tags: k8s
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: add Google GPG key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: add k8s repo
  command: echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list

- name: update packages
  apt:
    update_cache: true

- name: install k8s packages
  tags: k8s
  apt:
    name:
      - kubeadm
      - kubectl
      - kubelet
    state: present

- name: enable kubelet service, and enable persistently
  service:
    name: kubelet
    enabled: yes

# https://www.linuxsysadmins.com/install-kubernetes-cluster-with-ansible/
